### ISSUE TITLE
Users don't respond to updates for certain push notifications

### ISSUE THREAD

**Issue by jordanbuschman** [allollama/Orderly#3]
POSSIBLE ISSUE LOCATION: The order of the users listed in the UPDATE_ORDER push notification determines whether or not an app responds to a push notification (if a user is listed first, they assume they sent the push notification, and thus don't respond).

**Comment by allollama** [comment]
I think this was fixed?

**Comment by jordanbuschman** [comment]
Fixed, dawg.
