### ISSUE TITLE
Submitting sometimes doesn't work

### ISSUE THREAD

**Issue by jordanbuschman** [allollama/Orderly#5]
"Order pending" screen is fucked

**Comment by jordanbuschman** [comment]
It breaks if you go back from an order and then join the ordering group again

**Comment by allollama** [comment]
"if (object[@"submitted"] == [NSNumber numberWithBool:NO])" is true in User.m orderCompleted even though didn't go back and forth. Something wrong with the server?

**Comment by allollama** [comment]
"Recieved silent push notification with no specified action (could be a push notification you just sent)."

got the above instead of [userInfo[@"aps"][@"category"] isEqualToString:@"MOVE_TO_PAYMENT"]
